# Generated by Django 4.1.4 on 2023-06-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupones',
            new_name='Cupon',
        ),
    ]
