# Generated by Django 4.1.4 on 2023-06-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0006_boleta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='descuento',
            field=models.IntegerField(null=True, verbose_name='Descuento'),
        ),
    ]
