# Generated by Django 4.1.4 on 2023-06-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_alter_carro_options_alter_region_options'),
        ('ventaApp', '0007_boleta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.direccion', verbose_name='Direccion'),
        ),
    ]
