# Generated by Django 4.1.4 on 2023-06-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_alter_carro_options_alter_region_options'),
        ('ventaApp', '0008_boleta_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='productos',
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(to='userApp.carro', verbose_name='Productos'),
        ),
    ]
