# Generated by Django 4.1.4 on 2023-06-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0009_remove_boleta_productos_boleta_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='iva',
            field=models.IntegerField(null=True, verbose_name='Iva'),
        ),
    ]
