# Generated by Django 4.1.4 on 2023-06-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0010_alter_boleta_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.cupon', verbose_name='Cupon'),
        ),
    ]
