# Generated by Django 4.1.4 on 2023-06-21 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerApp', '0008_alter_categoria_options_alter_tallaeur_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0013_tarjeta'),
        ('ventaApp', '0011_alter_boleta_cupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='cupon',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='productos',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.cupon', verbose_name='Cupon')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.direccion', verbose_name='Direccion')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakerApp.zapatilla', verbose_name='Producto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.venta', verbose_name='Productos'),
        ),
    ]
