# Generated by Django 4.1.4 on 2023-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0012_remove_boleta_cupon_remove_boleta_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='numero_tarjeta',
            field=models.CharField(max_length=255, null=True, verbose_name='Numero Tarjeta'),
        ),
    ]
