# Generated by Django 4.1.4 on 2023-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0013_boleta_numero_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha_actual',
            field=models.DateField(auto_now=True, verbose_name='Fecha Actual'),
        ),
    ]
