# Generated by Django 4.1.4 on 2023-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0015_alter_boleta_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='boleta',
            name='estado_envio',
            field=models.IntegerField(null=True, verbose_name='Estado Envio'),
        ),
    ]
