# Generated by Django 4.1.4 on 2023-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_remove_usuario_direccion_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, verbose_name='Regiones')),
            ],
        ),
    ]
