# Generated by Django 4.1.4 on 2023-06-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.CharField(max_length=150, null=True, verbose_name='Region'),
        ),
    ]
