# Generated by Django 4.2.1 on 2023-06-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0003_alter_cupon_valor'),
        ('userApp', '0007_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.cupon'),
        ),
    ]
