# Generated by Django 4.1.4 on 2023-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_carro_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='direccion',
            field=models.CharField(max_length=150, null=True, verbose_name='Direccion'),
        ),
    ]
