# Generated by Django 4.1.4 on 2023-06-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_tarjeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
    ]
