# Generated by Django 4.1.4 on 2023-05-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo US/EUR')),
                ('number', models.IntegerField(verbose_name='Número de talla')),
            ],
        ),
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(default=0, verbose_name='Valor')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakerApp.categoria', verbose_name='Categoría')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakerApp.talla', verbose_name='Talla')),
            ],
        ),
    ]
