# Generated by Django 4.1.4 on 2023-05-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerApp', '0002_tallaeur_tallaus_remove_zapatilla_talla_delete_talla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapatilla',
            name='tallaUS',
        ),
        migrations.DeleteModel(
            name='TallaUS',
        ),
    ]
