# Generated by Django 4.1.4 on 2023-05-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerApp', '0003_remove_zapatilla_tallaus_delete_tallaus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zapatilla',
            options={'verbose_name': 'Zapatilla', 'verbose_name_plural': 'Zapatillas'},
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='imagen',
            field=models.ImageField(default='null', upload_to='', verbose_name='Imagen'),
        ),
    ]
