# Generated by Django 4.2.2 on 2023-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerApp', '0007_zapatilla_imagen_muestra_zapatilla_imagen_muestra_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='tallaeur',
            options={'verbose_name': 'Talla EUR', 'verbose_name_plural': 'Tallas EUR'},
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
