# Generated by Django 4.1.4 on 2023-06-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerApp', '0008_alter_categoria_options_alter_tallaeur_options'),
        ('sneakerApp', '0008_alter_categoria_options_alter_tallaeur_options_and_more'),
    ]

    operations = [
    ]
