# Generated by Django 4.1.4 on 2023-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('nro_pedido', models.CharField(max_length=200, null=True)),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('mensaje', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contactanos',
            },
        ),
    ]
