# Generated by Django 4.1.4 on 2023-06-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactanos',
            name='telefono',
        ),
    ]
