# Generated by Django 4.1.4 on 2023-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_remove_contactanos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactanos',
            name='celular',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
