# Generated by Django 4.1.4 on 2023-06-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_contactanos_celular_contactanos_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='asunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='nro_pedido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
