# Generated by Django 4.1.4 on 2023-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_alter_contactanos_asunto_alter_contactanos_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='mensaje',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
